### ISSUE TITLE
Filter/Select certain sportsbooks to show

### ISSUE THREAD

**Issue by tomm3hgunn** [tomm3hgunn/Jayhawk-Go#15]
May want to focus on 4-5 important sportsbooks. Can pre-filter the data in views.py by modifying the json variable, or if-statements in the html to show only the sportsbooks we choose.

**Comment by mrpete5** [comment]
Need to rename William Hill (US) to Caesars Sportsbook

**Comment by tomm3hgunn** [comment]
Good catch. API has it has william, so if u can add an manual name change in the code that would be good.
