### ISSUE TITLE
Add relevant information to the Home Page

### ISSUE THREAD

**Issue by tomm3hgunn** [tomm3hgunn/Jayhawk-Go#20]
Home page currently has templated text. Change it to be relevant to us or the Odds. Use API data to highlight a game or two along with news if possible. Similar to the figma design, add a section somewhere to highlight the 5 sportsbooks we are using. Have their name, logo (clickable to go to their site), short description, and their sign-up bonus if they have one.

Primary files to reference/work on:
/Jayhawk-Go/goforless/oddsAndEvents/sportz/index.html

**Comment by mrpete5** [comment]
@tomm3hgunn Do we still want the bookmaker logos/info as you described? I'm currently satisfied with index, but open to changes. We can close this if you don't want that anymore.

**Comment by tomm3hgunn** [comment]
Yes I think it is worth highlighting the 5 sportsbooks we are using and a link to their site.

**Comment by mrpete5** [comment]
My idea for where the 5 sportsbooks should be is after the games data and just before the footer. Plenty of room for creativity with the display of info.

![image](https://user-images.githubusercontent.com/15926744/202818794-bdccfa9e-2814-455e-99f3-5ce2765ed1d8.png)

**Comment by mrpete5** [comment]
I'm going to add the sportsbooks info to the bottom of index
