### ISSUE TITLE
Display Totals in matches.html

### ISSUE THREAD

**Issue by tomm3hgunn** [tomm3hgunn/Jayhawk-Go#21]
Similar to the currently implemented Spreads Pane, display the necessary data for Totals in the totals pane. Inside the matches.html, look for the comment PANE 1 to see how the Spreads data was displayed. Do your work under the PANE 2 comment. The format of the row may need to be modified as the Totals data may need to be presented differently compared to Spreads.

Display all the data and columns for totals as seen in http://127.0.0.1:8000/apiDisplay/totals/
![Screen Shot 2022-11-14 at 7 26 00 PM](https://user-images.githubusercontent.com/57208697/201803742-ff6da013-dfe8-40dd-a98c-2feff16ebb5d.png)

Recommended extension: Better comments (used to see different colored comments when starting with symbols !, ?, *, TODO)
![Screen Shot 2022-11-14 at 7 23 55 PM](https://user-images.githubusercontent.com/57208697/201803438-c36658d6-2da8-494e-a99c-ad0d56aa72a4.png)

What should be changed in http://127.0.0.1:8000/oddsAndEvents/matches:
![Screen Shot 2022-11-14 at 7 20 43 PM](https://user-images.githubusercontent.com/57208697/201802995-f8576d7f-b0e5-4d58-966c-96a0c9047945.png)

Primary files to reference/work on:
/Jayhawk-Go/goforless/apiDisplay/totals.html
/Jayhawk-Go/goforless/apiDisplay/views.py
/Jayhawk-Go/goforless/oddsAndEvents/sportz/matches.html
/Jayhawk-Go/goforless/oddsAndEvents/views.py

**Comment by mrpete5** [comment]
@tomm3hgunn @TrueSpecter This issue appears to be complete. If you confirm it is, please close it.

**Comment by tomm3hgunn** [comment]
Complete
