### ISSUE TITLE
Make the hoverable matches clickable to go to new page

### ISSUE THREAD

**Issue by tomm3hgunn** [tomm3hgunn/Jayhawk-Go#24]
For Spreads, Totals, or Moneyline, allow user to click on the hoverable row to go to a new page. This page will have all information corresponding to the two teams selected. Ideally, it will have their upcoming games, live games, past games, and all their odds.

Will need to make variable Django links to automate the page process, create Django specific templated pages to have a universal way to do all teams automatically.

**Comment by mrpete5** [comment]
@tomm3hgunn Is this issue complete? Please close if it is.
