### ISSUE TITLE
Create Odds and Events Logo and replace Jayhawk GO logo

### ISSUE THREAD

**Issue by mrpete5** [tomm3hgunn/Jayhawk-Go#27]
Logo in upper left corner which links back to index should be for our project, not our group. Group logo can go on about us and contact us pages.

**Comment by tomm3hgunn** [comment]
I think coding some features might be higher priority over designing, which takes alot of time.

**Comment by tomm3hgunn** [comment]
Added to index.html, need to add to rest of pages.
