### ISSUE TITLE
Displaying incorrect spreads data due to API abnormality

### ISSUE THREAD

**Issue by mrpete5** [tomm3hgunn/Jayhawk-Go#47]
The spreads data and potentially more (I haven't checked all the other data), is occasionally swapping the values ( the +/-) for some games. The API has inconsistency with it's nesting order. This means we need alternative checks to verify with order the nesting is taking to ensure accuracy.

Incorrect Example:
![image](https://user-images.githubusercontent.com/15926744/202792068-7648a9e3-9180-45af-884e-f67dbda55155.png)
![image](https://user-images.githubusercontent.com/15926744/202792460-c9249c44-2eb7-4d8b-abcb-0ce4dabe4609.png)

Correct Example:
![image](https://user-images.githubusercontent.com/15926744/202791893-2b808008-a1dc-482b-b470-ac0ff08e768a.png)
![image](https://user-images.githubusercontent.com/15926744/202792354-cdeb643c-7221-4cd1-9503-7e5c77b453ef.png)

Probable Functions in matches.html:
![image](https://user-images.githubusercontent.com/15926744/202791686-7577700b-2fc3-4459-8097-a9addeaeb22e.png)

**Comment by tomm3hgunn** [comment]
Need to do it for matchup.html
