### ISSUE TITLE
Add login and registration options

### ISSUE THREAD

**Issue by mrpete5** [tomm3hgunn/Jayhawk-Go#48]
I'm currently just in the research stage. Feel free to help. Issue might be reassigned to someone else once more is known.

**Comment by tomm3hgunn** [comment]
Planning on researching on this too

**Comment by mrpete5** [comment]
1: https://www.section.io/engineering-education/django-google-oauth/
2: https://dev.to/mdrhmn/django-google-authentication-using-django-allauth-18f8

@tomm3hgunn These two links look like they would probably work. I could attempt it, but there are probably parts that you'd need to do. Let me know.

**Comment by mrpete5** [comment]
@tomm3hgunn The login functionality needs some work. Can you look at it? Logout seems good. I'll add this to all the other pages (only on index now) once it's working right.

**Comment by tomm3hgunn** [comment]
Reviewing

**Comment by mrpete5** [comment]
Need to fix the login sequencing. Also, add the login/logout header menu option like it is in index to all other pages once it's completed on index.

**Comment by mrpete5** [comment]
@tomm3hgunn Should we create basic pages that look more like our current template for the whole suite of pages associated with logging in including:
http://127.0.0.1:8000/oddsAndEvents/accounts/login/ , http://127.0.0.1:8000/oddsAndEvents/accounts/password/reset/ , http://127.0.0.1:8000/oddsAndEvents/accounts/signup/ , http://127.0.0.1:8000/oddsAndEvents/accounts/google/login/ , http://127.0.0.1:8000/oddsAndEvents/accounts/social/signup/ , and any other ones?

My thoughts were it should have the bare bones template like matchups without any background image, and just the header menu and footer.

**Comment by mrpete5** [comment]
I'll do a mock up for http://127.0.0.1:8000/oddsAndEvents/accounts/login/

**Comment by mrpete5** [comment]
@tomm3hgunn I'm unsure how to make the login sequence any better than it currently is. I'll leave this issue to you, but if it stays the same I'd be fine with that.

**Comment by mrpete5** [comment]
@tomm3hgunn With the merge of preference_branch into dev from issue #50, this issue should be complete as well
