### ISSUE TITLE
Add user preference features

### ISSUE THREAD

**Issue by mrpete5** [tomm3hgunn/Jayhawk-Go#50]
After the registration and login is completed. Need to brainstorm ideas for preference features. Only idea I have is a time zone setting which aligns with the game start times throughout the site.

**Comment by tomm3hgunn** [comment]
Maybe letting the user pick certain teams to follow, and it'd be its own page with only the chosen teams.

**Comment by mrpete5** [comment]
Researching time zone features. Probably will start a preference page on a new branch.

**Comment by tomm3hgunn** [comment]
Django has timezone awareness when pulling from the db. See https://docs.djangoproject.com/en/4.1/topics/i18n/timezones/

**Comment by mrpete5** [comment]
I started setting up a preferences page, but holding off on further work for a while. Feel free to jump in. It's the preference_branch

**Comment by mrpete5** [comment]
@tomm3hgunn Awaiting check and merge with dev

**Comment by tomm3hgunn** [comment]
@mrpete5 Go ahead and make a pull request. Thats when I can check and merge
